title: MAJID JANGANI
description: Portfolio Construction And Optimization
show_downloads: true
theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
plugins:
  - jekyll-remote-theme
permalink: /:title/
baseurl: "/Portfolio-Construction-Optimization-"
